"""add_brand_column_to_product_table

Revision ID: 0435e28af7bb
Revises: 1ec9f33a6a8c
Create Date: 2025-08-08 16:19:27.448065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0435e28af7bb'
down_revision = '1ec9f33a6a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
